# Generated by Django 4.2.2 on 2023-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, null=True)),
                ("phoneno", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=20, null=True)),
                ("msg", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="registration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, null=True)),
                ("phoneno", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=20, null=True)),
                ("c_programming", models.BooleanField(default=False)),
                ("java", models.BooleanField(default=False)),
                ("html_css", models.BooleanField(default=False)),
                ("python", models.BooleanField(default=False)),
                ("react_js", models.BooleanField(default=False)),
                ("sql", models.BooleanField(default=False)),
                ("cpp", models.BooleanField(default=False)),
                ("mongodb", models.BooleanField(default=False)),
                ("program_period", models.CharField(max_length=20, null=True)),
                ("card_number", models.CharField(max_length=16, null=True)),
                ("cvv", models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
